# Generated by Django 6.0.2 on 2026-02-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_populate_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='age',
            field=models.IntegerField(default=30, help_text="Provider's age"),
        ),
    ]
