# Generated by Django 6.0.2 on 2026-02-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_populate_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy / On Job'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
    ]
