# Generated by Django 6.0.2 on 2026-02-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_serviceprovider_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
