# Generated by Django 6.0.2 on 2026-02-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_transaction_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional details from the user'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_location',
            field=models.CharField(blank=True, help_text='Where the service should be provided', max_length=255),
        ),
    ]
