# Generated by Django 6.0.2 on 2026-02-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_booking_notes_booking_service_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_services',
            field=models.TextField(blank=True, help_text='List of services selected by the user', null=True),
        ),
    ]
