# Generated by Django 6.0.2 on 2026-02-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_booking_selected_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (Unpaid)'), ('paid', 'Paid (Awaiting Acceptance)'), ('confirmed', 'Confirmed (Partner Accepted)'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
