# Generated by Django 6.0.2 on 2026-02-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Requested (Waiting for Partner)'), ('confirmed', 'In Progress (Accepted)'), ('service_done', 'Service Done (Awaiting Payment)'), ('paid', 'Paid (Awaiting Verification)'), ('completed', 'Finished & Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
