# Generated by Django 6.0.2 on 2026-02-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='start_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Requested (Waiting for Partner)'), ('accepted', 'Accepted (Waiting for OTP)'), ('confirmed', 'In Progress (Work Started)'), ('service_done', 'Service Done (Awaiting Payment)'), ('paid', 'Paid (Awaiting Verification)'), ('completed', 'Finished & Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
